using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ensaf.Web.ApiModels
{
    public class PostDTO : CreatePosttDTO
    {
        public int Id { get; set; }
    }

    // Creation DTOs should not include an ID if the ID will be generated by the back end
    public class CreatePosttDTO
    {
        public string Title { get; set; }
        public string Body { get; set; }

    }
}
